function error_obs_only = error_obs_only(X,Y,Z,fx,fy,rx,ry,rz,tx,ty,tz,u0,u_obs,v0,v_obs)
%ERROR_OBS_ONLY
%    ERROR_OBS_ONLY = ERROR_OBS_ONLY(X,Y,Z,FX,FY,RX,RY,RZ,TX,TY,TZ,U0,U_OBS,V0,V_OBS)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Sep-2021 18:00:01

t2 = rx.^2;
t3 = ry.^2;
t4 = rz.^2;
t5 = t2+t3;
t6 = t4+t5;
t7 = 1.0./t6;
t8 = sqrt(t6);
t9 = 1.0./t8;
t10 = cos(t8);
t11 = sin(t8);
t12 = t10-1.0;
t13 = rx.*t9.*t11;
t14 = ry.*t9.*t11;
t15 = rz.*t9.*t11;
t16 = rx.*ry.*t7.*t12;
t17 = rx.*rz.*t7.*t12;
t18 = ry.*rz.*t7.*t12;
t20 = t5.*t7.*t12;
t19 = -t18;
t21 = t20+1.0;
t23 = t14+t17;
t22 = Z.*t21;
t24 = X.*t23;
t25 = t13+t19;
t26 = -t24;
t27 = Y.*t25;
t28 = t22+t26+t27+tz;
t29 = 1.0./t28;
error_obs_only = [-u_obs+t29.*(-X.*(t23.*u0-fx.*(t7.*t12.*(t3+t4)+1.0))+fx.*tx+tz.*u0-Y.*(fx.*(t15+t16)-t25.*u0)+Z.*(t21.*u0+fx.*(t14-t17)));-v_obs+t29.*(Y.*(t25.*v0+fy.*(t7.*t12.*(t2+t4)+1.0))+fy.*ty+tz.*v0-Z.*(fy.*(t13+t18)-t21.*v0)-X.*(t23.*v0-fy.*(t15-t16)))];
